jobs:
  update-flake:
    name: Run update-flake
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run flake#update-packages
        run: |
          nix run .#fetch-all
      - name: Run flake#update-packages
        run: |
          nix run nixpkgs#npins -- upgrade
          nix run nixpkgs#npins -- update
      - name: Run flake#fmt
        run: |
          nix fmt
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A

          if ! git diff --cached --quiet; then
            git commit -m "flake: updated nix-packages [automated]"
            git push
          else
            echo "No changes from updater"
          fi
name: Update Nix flake
"on":
  workflow_dispatch: {}
permissions:
  contents: write
